# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3357b4eb8eaf1cac07d427e60be0164189ed9f9b30e095d557bce3b8bfab29d7eb67e82bffc10edf4e520668995bc1fd2f168f8f08fa5dff3f7f1259eff120

test:
  secret_key_base: d0f9c0d48acf41907691f4632542fa0f97a6c27ed089170424f0f34e82fe1766c90d586cd49c5eadae251591181d5ffa473b030e3360ec5f48d6333a274ead86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
